# Generated by Django 4.0.5 on 2023-02-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_of_account',
            fields=[
                ('Account_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Main_Code', models.CharField(max_length=5, null=True)),
                ('Sub_Code', models.CharField(max_length=5, null=True)),
                ('Dept_Code', models.CharField(max_length=5, null=True)),
                ('Account_Description', models.CharField(max_length=100, null=True)),
                ('Account_Type', models.CharField(max_length=100, null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.CharField(max_length=100, null=True)),
                ('Updated_on', models.DateTimeField(null=True)),
                ('Updated_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_Code', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(max_length=30, null=True)),
                ('Description', models.TextField(max_length=255, null=True)),
                ('Address', models.TextField(max_length=50, null=True)),
                ('Logo', models.CharField(max_length=18, null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.CharField(max_length=100, null=True)),
                ('Updated_on', models.DateTimeField(null=True)),
                ('Updated_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Party_Type',
            fields=[
                ('Party_Type_Code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Is_Enabled', models.CharField(max_length=1, null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.CharField(max_length=100, null=True)),
                ('Updated_on', models.DateTimeField(null=True)),
                ('Updated_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Voucher_Type',
            fields=[
                ('Voucher_Type_Code', models.BigAutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Is_Enabled', models.CharField(max_length=1, null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.CharField(max_length=100, null=True)),
                ('Updated_on', models.DateTimeField(null=True)),
                ('Updated_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher_Main',
            fields=[
                ('Trans_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Voucher_No', models.CharField(max_length=100, null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.CharField(max_length=100, null=True)),
                ('Voucher_Type_Code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='V_Type_Code', to='Account.ref_voucher_type')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Debit', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('Credit', models.DecimalField(decimal_places=3, max_digits=13, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('Account_No', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ac_No', to='Account.chart_of_account')),
                ('Trans_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transection_id', to='Account.voucher_main')),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Party_Profile',
            fields=[
                ('Party_Code', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=500, null=True)),
                ('NTN_No', models.CharField(max_length=50, null=True)),
                ('Phone_No', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('Payment_Terms', models.CharField(max_length=500, null=True)),
                ('Created_on', models.DateTimeField(null=True)),
                ('Created_by', models.CharField(max_length=100, null=True)),
                ('Updated_on', models.DateTimeField(null=True)),
                ('Updated_by', models.CharField(max_length=100, null=True)),
                ('Account_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Acc_No', to='Account.chart_of_account')),
                ('Party_Type_Code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_Code', to='Account.ref_party_type')),
            ],
        ),
    ]
